### ISSUE TITLE
env_dev failed with 1

### ISSUE THREAD

**Issue by danactive** [iamawong-zz/cards-against-humanity#21]
I'm tried to run in dev mode.  Though the "npm run-script dev" throws an error:

12 info cards-against-humanity@0.0.1 Failed to exec dev script
13 error cards-against-humanity@0.0.1 dev: `./env_dev`
13 error `cmd "/c" "./env_dev"` failed with 1

Any ideas?

OS: Windows 7 64bit

**Comment by iamawong-zz** [comment]
Hrm, I've never run into that issue before. What happens if you just try to run supervisor server.js

**Comment by danactive** [comment]
Difficult error to read, but looks like the client.js path is wrong

**Comment by iamawong-zz** [comment]
Is there one in your /public dir?

**Comment by danactive** [comment]
No, it's in the client folder

**Comment by iamawong-zz** [comment]
When you start up with 'supervisor server.js', it calls upon initialize.js which copies client.js to the public directory. May I see the error? I've never tried to run this on a windows machine, sorry.

**Comment by danactive** [comment]
![supervisor_loop](https://f.cloud.github.com/assets/1093286/63792/3554aa90-5e08-11e2-934c-dd38a4cbcc23.JPG)

This error loops so it's a pain

**Comment by iamawong-zz** [comment]
So the issue is that it's trying to look for the following file path: 
C:\Users\dan\github\cards-against-humanity\C:\Users\dan\github\cards-against-humanity\client\client.js 
while it probably should be looking for...
C:\Users\dan\github\cards-against-humanity\client\client.js

There seems to be some compatibility issues in what is happening with __dirname or whatnot with this line 24 in initialize.js

**Comment by danactive** [comment]
Yes, that's the doubling out path I saw too
